repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff-check
        args: [--fix, --config=config/ruff.toml]
      - id: ruff-format
        args: [--config=config/ruff.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.19.1"
    hooks:
      - id: mypy
        args: [--config-file=config/mypy.ini]
